[package]
name = "basic-audio-filters"
version = "0.1.0"
authors = ["DGriffin91 <github@dgdigital.net>"]
edition = "2018"
description = "Filters for real-time audio"
license = "MIT/Apache-2.0"

[dependencies]
num-complex = "0.4"